bin = 'AppReadWriteCounter.exe'
description = 'AppReadWriteCounter is a tool for Windows that counts and displays the current file read / write operations of every application running on your system. It displays the number of read/write bytes, the number of read/write operations, current calculated read/write speed, and the details about the application (product name, product version, and so on) that makes the file read/write operations.'
hash = 'e19833dbb79552be46a30f62c90cdd8ce9f97b4097beed2fa1b3c84402ea1ce5'
homepage = 'https://www.nirsoft.net/utils/app_read_write_counter.html'
license = 'freeware'
persist = [ 'AppReadWriteCounter.cfg', 'AppReadWriteCounter_lng.ini' ]
pre_install = [
    'if (!(Test-Path "$persist_dir\AppReadWriteCounter.cfg")) { New-Item "$dir\AppReadWriteCounter.cfg" | Out-Null }',
    'if (!(Test-Path "$persist_dir\AppReadWriteCounter_lng.ini")) { New-Item "$dir\AppReadWriteCounter_lng.ini" | Out-Null }'
]
shortcuts = [ [ 'AppReadWriteCounter.exe', 'AppReadWriteCounter' ] ]
url = 'https://www.nirsoft.net/utils/appreadwritecounter-x64.zip'
version = '1.25'