description = 'Animated sprite editor & pixel art tool'
hash = 'F82C2486398CB34744E140FEB9BC53BB3D704FD2CF5731DF834CD12C08893D8C'
homepage = 'https://www.aseprite.org/'
shortcuts = [ [ 'aseprite.exe', 'Aseprite' ] ]
url = 'https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBcVRIUGpuMVhnTTFnczRhLVZhSFM3R2RmOUJ1RXc_ZT1jR0pSemE.7z'
version = '1.2.27'