bin = [ [ 'ccdown.exe', 'ccdown' ] ]
checkver = 'github'
description = '一个用于下载B站(哔哩哔哩)CC字幕及转换的工具'
hash = 'FC2503D21164096BC8C8D7885A2351A92B562EF36094876516A3865ADC24511C'
homepage = 'https://github.com/nathanli97/BiliBiliCCSubtitle'
license = 'Apache-2.0 license'
url = 'https://github.com/nathanli97/BiliBiliCCSubtitle/releases/latest/download/BiliBiliCCSubtitle-x86_64.zip'
version = '1.1.4'