bin = 'UsbEAm Hosts Editor v3.50.exe'
extract_dir = 'UsbEAm Hosts Editor'
hash = '2def3989a6d4f9736535fd57d938f35c9b22bce11613ffd4b5a0189f11d99d99'
homepage = 'https://www.dogfight360.com/blog/475/'
shortcuts = [ [ 'UsbEAm Hosts Editor v3.50.exe', 'UsbEAm Hosts Editor v3.50' ] ]
url = 'https://www.dogfight360.com/blog/wp-content/uploads/2017/03/UsbEAm-Hosts-Editor-v3.50.zip'
version = '3.50'