description = 'VisualSFM : A Visual Structure from Motion System. (*for nVidia CUDA)'
extract_dir = 'VisualSFM_windows_cuda_64bit'
hash = '78280900F9AAC1D16FE7935087B80D1592FF5E9670EF15D39655E5242AE6DE3B'
homepage = 'http://ccwu.me/vsfm/'
shortcuts = [ [ 'VisualSFM.exe', 'VisualSFM' ] ]
url = 'http://ccwu.me/vsfm/download/VisualSFM_windows_cuda_64bit.zip'
version = '0.5.26'

[autoupdate]
url = 'http://ccwu.me/vsfm/download/VisualSFM_windows_cuda_64bit.zip'